name: nox
on: [push, pull_request]
jobs:
  nox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            swig \
            gfortran \
            libinput-dev \
            libdbus-1-dev \
            libglib2.0-dev \
            libjpeg-dev \
            zlib1g-dev \
            libtiff-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libwebp-dev \
            libopenjp2-7-dev \
            libindi-dev \
            libopenblas-dev \
            liblapack-dev

      - uses: wntrblm/nox@2024.04.15
        with:
          python-versions: "3.9"

      - run: nox -s lint format type_hints smoke_tests unit_tests
